apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: osandanavoda/week5task:1.1.1
    name: pkk
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  